import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  buildTokenDocumentation,
  flattenTokenValues,
  generateTokenDocumentation,
  toKebabCase,
} from "../../../scripts/generateTokenDocs.js";

const autoGeneratedNotice =
  "<!-- AUTO-GENERATED by scripts/generateTokenDocs.js.";

const extractTokenPaths = (page: string) =>
  Array.from(
    page.matchAll(/<tr data-token-path="([^"]+)">/g),
    ([, tokenPath]) => tokenPath,
  );

describe("Token documentation generator", () => {
  it("keeps an exact, duplicate-free inventory for every public token group", () => {
    const { inventory } = buildTokenDocumentation();

    expect(inventory.global).toHaveLength(600);
    expect(inventory.components).toHaveLength(679);
    expect(inventory.componentGroups).toHaveLength(61);
    expect(inventory.custom).toHaveLength(52);
    expect(inventory.agGrid).toHaveLength(225);

    for (const [group, tokenPaths] of Object.entries(inventory)) {
      expect(new Set(tokenPaths).size, `${group} should be unique`).toBe(
        tokenPaths.length,
      );
    }
  });

  it("renders every inventory item exactly once in the four generated pages", () => {
    const { files, inventory } = buildTokenDocumentation();
    const globalPage = files["docs/tokens.md"];
    const componentPage = files["docs/tokens/components.md"];
    const customPage = files["docs/tokens/custom.md"];
    const agPage = files["docs/tokens/ag-grid-table.md"];

    expect(Object.keys(files)).toHaveLength(4);
    for (const page of Object.values(files)) {
      expect(page).toContain(autoGeneratedNotice);
    }

    expect(globalPage).toContain(
      '<code src="./tokens/demo/global.tsx">',
    );
    expect(componentPage).toContain(
      '<code src="./demo/components.tsx">',
    );
    expect(customPage).toContain(
      '<code src="./demo/custom.tsx">',
    );
    expect(agPage).toContain('<code src="./demo/ag-grid-table.tsx">');

    const expectedRows = [
      [globalPage, inventory.global.length],
      [componentPage, inventory.components.length],
      [customPage, inventory.custom.length],
      [agPage, inventory.agGrid.length],
    ] as const;

    for (const [page, expectedCount] of expectedRows) {
      const tokenPaths = extractTokenPaths(page);
      expect(tokenPaths).toHaveLength(expectedCount);
      expect(new Set(tokenPaths).size).toBe(expectedCount);
    }
  });

  it("documents representative global, component, and Grid tokens", () => {
    const { files, inventory } = buildTokenDocumentation();

    expect(inventory.global).toEqual(
      expect.arrayContaining(["guotai blue6", "guozhi blue6", "emptyBorder"]),
    );
    expect(files["docs/tokens.md"]).toContain(
      'data-token-path="guotai blue6"',
    );
    expect(files["docs/tokens.md"]).toContain(
      'data-token-path="guozhi blue6"',
    );
    expect(files["docs/tokens.md"]).toContain("#0083FF");
    expect(files["docs/tokens.md"]).toContain("ECharts 使用全局 Token");

    expect(inventory.componentGroups).toEqual(
      expect.arrayContaining([
        "Sidebar",
        "PanelCollapse",
        "Hall",
        "Checkbox",
        "Global",
      ]),
    );
    expect(inventory.components).toEqual(
      expect.arrayContaining([
        "Card.colorBgCard",
        "Sidebar.itemHoverBg",
        "PanelCollapse.bg",
        "Hall.itemBgColor",
        "Hall.itemTextColor",
        "Hall.itemCodeColor",
        "Hall.dividerColor",
        "Hall.itemBgHoverColor",
        "Hall.itemBgActiveColor",
        "Radio.buttonColorBorder",
        "Checkbox.ColorBorder",
        "Global.themeMode",
      ]),
    );
    expect(files["docs/tokens/components.md"]).toContain(
      'data-token-path="Sidebar.itemHoverBg"',
    );
    expect(files["docs/tokens/components.md"]).toContain(
      'data-token-path="PanelCollapse.bg"',
    );
    expect(files["docs/tokens/components.md"]).toContain(
      'data-token-path="Hall.itemBgColor"',
    );
    expect(files["docs/tokens/components.md"]).toContain(
      'data-token-path="Checkbox.ColorBorder"',
    );

    expect(inventory.agGrid).toContain("accentColor");
    expect(inventory.agGrid).toEqual(
      expect.arrayContaining([
        "rowGroupBgColor",
        "radioCheckedShapeImage",
        "widgetContainerVerticalSpacing",
      ]),
    );
    expect(files["docs/tokens/ag-grid-table.md"]).toContain(
      'data-token-path="accentColor"',
    );
    expect(files["docs/tokens/ag-grid-table.md"]).toContain(
      "图表统一使用 ECharts",
    );
  });

  it("documents every gzd AG Grid extension token", () => {
    const { files, inventory } = buildTokenDocumentation();
    const extensionTokenNames = [
      "checkboxCheckedColor",
      "chromeForegroundColor",
      "dropdownBorderRadius",
      "headerBorderColor",
      "inputDisabledBorderLegacy",
      "inputRightIconVisible",
      "radioCheckedShapeImage",
      "rowGroupBgColor",
      "rowGroupBgHoverColor",
      "scrollbarThumbColor",
      "scrollbarThumbHoverColor",
      "tabBorderColor",
      "widgetContainerBorderRadius",
      "widgetContainerVerticalSpacing",
    ];

    for (const tokenName of extensionTokenNames) {
      expect(inventory.agGrid, tokenName).toContain(tokenName);
      expect(files["docs/tokens/ag-grid-table.md"], tokenName).toContain(
        `data-token-path="${tokenName}"`,
      );
    }
  });

  it("uses one-based paths for arrays and runtime-compatible CSS names", () => {
    expect(
      flattenTokenValues({
        palette: {
          fills: ["#111111", "#222222"],
        },
      }),
    ).toEqual([
      {
        pathParts: ["palette", "fills", "1"],
        value: "#111111",
      },
      {
        pathParts: ["palette", "fills", "2"],
        value: "#222222",
      },
    ]);

    expect(toKebabCase("guotai blue1")).toBe("guotai-blue-1");
    expect(toKebabCase("PanelCollapse")).toBe("panel-collapse");
    expect(toKebabCase("itemHoverBg")).toBe("item-hover-bg");
  });

  it("keeps one Dumi-level theme source for every Token demo", () => {
    const demoFiles = [
      "docs/tokens/demo/global.tsx",
      "docs/tokens/demo/components.tsx",
      "docs/tokens/demo/custom.tsx",
      "docs/tokens/demo/ag-grid-table.tsx",
    ];

    for (const demoFile of demoFiles) {
      const demoSource = readFileSync(demoFile, "utf8");
      expect(demoSource).not.toContain("<ConfigProvider");
      expect(demoSource).not.toContain("<select");
      expect(demoSource).not.toContain("当前主题");
    }

    const globalDemo = readFileSync(demoFiles[0], "utf8");
    const agGridDemo = readFileSync(demoFiles[3], "utf8");
    const dumiApp = readFileSync(".dumi/app.tsx", "utf8");

    expect(globalDemo).toContain("theme.useToken()");
    expect(agGridDemo).toContain("<Table<RowData>");
    expect(agGridDemo).not.toMatch(/getDesignTokens|globalToken|theme=\{/);
    expect(dumiApp).toContain("rootContainer");
    expect(dumiApp).toContain(
      "<ConfigProvider themeMode={docsThemeSelectionToMode(selection)}>",
    );
    expect(dumiApp).toContain("includeCustom: true");
  });

  it("confirms committed documentation matches the generator", () => {
    expect(generateTokenDocumentation({ check: true }).staleFiles).toEqual([]);
  });
});
